Merging minor tweaks into master ahead of demo day
yopocho/VGA-Project pull request #26
Opened 2023-06-07 18:52 UTC by yopocho

2023-06-07 19:38 UTC, Sjoerddbb requested changes
Kan je in de readme nog bij use de uitleg over de functies en argumenten laten staan

2023-06-07 19:38 UTC, Sjoerddbb commented on README.md
Hier vallen wat dingen weg die wel nuttig zijn maar snap niet waarom mijn file niet de laatste info had. Kan je dit nog aanpassen aub

2023-06-07 19:58 UTC, Sjoerddbb reviewed
Thnx for fixing it

2023-06-07 19:58 UTC, yopocho commented on README.md
Solved the issue 👍

2023-06-08 06:25 UTC, rubenmiddelman approved these changes

2023-06-08 06:29 UTC, Sjoerddbb approved these changes
This is a nice code

2023-06-08 06:29 UTC, merged